on: push
# Пример для проекта на Node.js
jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3
      # Устанавливаем Node.js
      - uses: actions/setup-node@v3
      # Ставим зависимости
      - run: make setup
      # Запускаем линтер
      - run: make test 
      - run: make lint
      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets. SNYK_TOKEN }}
